// <auto-generated />
using System;
using EFCoreData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore3App.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20211126153653_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCoreEntities.Order<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nchar(32)")
                        .IsFixedLength()
                        .HasComment("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("名字");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("OrderNameIndex");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("EFCoreEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset")
                        .HasComment("创建时间");

                    b.Property<double>("DouV")
                        .HasColumnType("float")
                        .HasComment("浮点数");

                    b.Property<int>("IntV")
                        .HasColumnType("int")
                        .HasComment("整形");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("名字");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasComment("性别");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 0.10000000000000001,
                            IntV = 0,
                            Name = "Test0",
                            Sex = 0
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 1.1000000000000001,
                            IntV = 1,
                            Name = "Test1",
                            Sex = 0
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 2.1000000000000001,
                            IntV = 2,
                            Name = "Test2",
                            Sex = 0
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 3.1000000000000001,
                            IntV = 3,
                            Name = "Test3",
                            Sex = 0
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 4.0999999999999996,
                            IntV = 4,
                            Name = "Test4",
                            Sex = 0
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 5.0999999999999996,
                            IntV = 5,
                            Name = "Test5",
                            Sex = 0
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 6.0999999999999996,
                            IntV = 6,
                            Name = "Test6",
                            Sex = 0
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 7.0999999999999996,
                            IntV = 7,
                            Name = "Test7",
                            Sex = 0
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 8.0999999999999996,
                            IntV = 8,
                            Name = "Test8",
                            Sex = 0
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 9.0999999999999996,
                            IntV = 9,
                            Name = "Test9",
                            Sex = 0
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 10.1,
                            IntV = 10,
                            Name = "Test10",
                            Sex = 0
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 11.1,
                            IntV = 11,
                            Name = "Test11",
                            Sex = 0
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 12.1,
                            IntV = 12,
                            Name = "Test12",
                            Sex = 0
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 13.1,
                            IntV = 13,
                            Name = "Test13",
                            Sex = 0
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 14.1,
                            IntV = 14,
                            Name = "Test14",
                            Sex = 0
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 15.1,
                            IntV = 15,
                            Name = "Test15",
                            Sex = 0
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 16.100000000000001,
                            IntV = 16,
                            Name = "Test16",
                            Sex = 0
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 17.100000000000001,
                            IntV = 17,
                            Name = "Test17",
                            Sex = 0
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 18.100000000000001,
                            IntV = 18,
                            Name = "Test18",
                            Sex = 0
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 19.100000000000001,
                            IntV = 19,
                            Name = "Test19",
                            Sex = 0
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 20.100000000000001,
                            IntV = 20,
                            Name = "Test20",
                            Sex = 0
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 21.100000000000001,
                            IntV = 21,
                            Name = "Test21",
                            Sex = 0
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 22.100000000000001,
                            IntV = 22,
                            Name = "Test22",
                            Sex = 0
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 23.100000000000001,
                            IntV = 23,
                            Name = "Test23",
                            Sex = 0
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 24.100000000000001,
                            IntV = 24,
                            Name = "Test24",
                            Sex = 0
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 25.100000000000001,
                            IntV = 25,
                            Name = "Test25",
                            Sex = 0
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 26.100000000000001,
                            IntV = 26,
                            Name = "Test26",
                            Sex = 0
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 27.100000000000001,
                            IntV = 27,
                            Name = "Test27",
                            Sex = 0
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 28.100000000000001,
                            IntV = 28,
                            Name = "Test28",
                            Sex = 0
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 29.100000000000001,
                            IntV = 29,
                            Name = "Test29",
                            Sex = 0
                        },
                        new
                        {
                            Id = 31,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 30.100000000000001,
                            IntV = 30,
                            Name = "Test30",
                            Sex = 0
                        },
                        new
                        {
                            Id = 32,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 31.100000000000001,
                            IntV = 31,
                            Name = "Test31",
                            Sex = 0
                        },
                        new
                        {
                            Id = 33,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 32.100000000000001,
                            IntV = 32,
                            Name = "Test32",
                            Sex = 0
                        },
                        new
                        {
                            Id = 34,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 33.100000000000001,
                            IntV = 33,
                            Name = "Test33",
                            Sex = 0
                        },
                        new
                        {
                            Id = 35,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 34.100000000000001,
                            IntV = 34,
                            Name = "Test34",
                            Sex = 0
                        },
                        new
                        {
                            Id = 36,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 35.100000000000001,
                            IntV = 35,
                            Name = "Test35",
                            Sex = 0
                        },
                        new
                        {
                            Id = 37,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 36.100000000000001,
                            IntV = 36,
                            Name = "Test36",
                            Sex = 0
                        },
                        new
                        {
                            Id = 38,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 37.100000000000001,
                            IntV = 37,
                            Name = "Test37",
                            Sex = 0
                        },
                        new
                        {
                            Id = 39,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 38.100000000000001,
                            IntV = 38,
                            Name = "Test38",
                            Sex = 0
                        },
                        new
                        {
                            Id = 40,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 39.100000000000001,
                            IntV = 39,
                            Name = "Test39",
                            Sex = 0
                        },
                        new
                        {
                            Id = 41,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 40.100000000000001,
                            IntV = 40,
                            Name = "Test40",
                            Sex = 0
                        },
                        new
                        {
                            Id = 42,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 41.100000000000001,
                            IntV = 41,
                            Name = "Test41",
                            Sex = 0
                        },
                        new
                        {
                            Id = 43,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 42.100000000000001,
                            IntV = 42,
                            Name = "Test42",
                            Sex = 0
                        },
                        new
                        {
                            Id = 44,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 43.100000000000001,
                            IntV = 43,
                            Name = "Test43",
                            Sex = 0
                        },
                        new
                        {
                            Id = 45,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 44.100000000000001,
                            IntV = 44,
                            Name = "Test44",
                            Sex = 0
                        },
                        new
                        {
                            Id = 46,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 45.100000000000001,
                            IntV = 45,
                            Name = "Test45",
                            Sex = 0
                        },
                        new
                        {
                            Id = 47,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 46.100000000000001,
                            IntV = 46,
                            Name = "Test46",
                            Sex = 0
                        },
                        new
                        {
                            Id = 48,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 47.100000000000001,
                            IntV = 47,
                            Name = "Test47",
                            Sex = 0
                        },
                        new
                        {
                            Id = 49,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 48.100000000000001,
                            IntV = 48,
                            Name = "Test48",
                            Sex = 0
                        },
                        new
                        {
                            Id = 50,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 49.100000000000001,
                            IntV = 49,
                            Name = "Test49",
                            Sex = 0
                        },
                        new
                        {
                            Id = 51,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 50.100000000000001,
                            IntV = 50,
                            Name = "Test50",
                            Sex = 0
                        },
                        new
                        {
                            Id = 52,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 51.100000000000001,
                            IntV = 51,
                            Name = "Test51",
                            Sex = 0
                        },
                        new
                        {
                            Id = 53,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 52.100000000000001,
                            IntV = 52,
                            Name = "Test52",
                            Sex = 0
                        },
                        new
                        {
                            Id = 54,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 53.100000000000001,
                            IntV = 53,
                            Name = "Test53",
                            Sex = 0
                        },
                        new
                        {
                            Id = 55,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 54.100000000000001,
                            IntV = 54,
                            Name = "Test54",
                            Sex = 0
                        },
                        new
                        {
                            Id = 56,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 55.100000000000001,
                            IntV = 55,
                            Name = "Test55",
                            Sex = 0
                        },
                        new
                        {
                            Id = 57,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 56.100000000000001,
                            IntV = 56,
                            Name = "Test56",
                            Sex = 0
                        },
                        new
                        {
                            Id = 58,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 57.100000000000001,
                            IntV = 57,
                            Name = "Test57",
                            Sex = 0
                        },
                        new
                        {
                            Id = 59,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 58.100000000000001,
                            IntV = 58,
                            Name = "Test58",
                            Sex = 0
                        },
                        new
                        {
                            Id = 60,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 59.100000000000001,
                            IntV = 59,
                            Name = "Test59",
                            Sex = 0
                        },
                        new
                        {
                            Id = 61,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 60.100000000000001,
                            IntV = 60,
                            Name = "Test60",
                            Sex = 0
                        },
                        new
                        {
                            Id = 62,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 61.100000000000001,
                            IntV = 61,
                            Name = "Test61",
                            Sex = 0
                        },
                        new
                        {
                            Id = 63,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 62.100000000000001,
                            IntV = 62,
                            Name = "Test62",
                            Sex = 0
                        },
                        new
                        {
                            Id = 64,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 63.100000000000001,
                            IntV = 63,
                            Name = "Test63",
                            Sex = 0
                        },
                        new
                        {
                            Id = 65,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 64.099999999999994,
                            IntV = 64,
                            Name = "Test64",
                            Sex = 0
                        },
                        new
                        {
                            Id = 66,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 65.099999999999994,
                            IntV = 65,
                            Name = "Test65",
                            Sex = 0
                        },
                        new
                        {
                            Id = 67,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 66.099999999999994,
                            IntV = 66,
                            Name = "Test66",
                            Sex = 0
                        },
                        new
                        {
                            Id = 68,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 67.099999999999994,
                            IntV = 67,
                            Name = "Test67",
                            Sex = 0
                        },
                        new
                        {
                            Id = 69,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 68.099999999999994,
                            IntV = 68,
                            Name = "Test68",
                            Sex = 0
                        },
                        new
                        {
                            Id = 70,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 69.099999999999994,
                            IntV = 69,
                            Name = "Test69",
                            Sex = 0
                        },
                        new
                        {
                            Id = 71,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 70.099999999999994,
                            IntV = 70,
                            Name = "Test70",
                            Sex = 0
                        },
                        new
                        {
                            Id = 72,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 71.099999999999994,
                            IntV = 71,
                            Name = "Test71",
                            Sex = 0
                        },
                        new
                        {
                            Id = 73,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 72.099999999999994,
                            IntV = 72,
                            Name = "Test72",
                            Sex = 0
                        },
                        new
                        {
                            Id = 74,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 73.099999999999994,
                            IntV = 73,
                            Name = "Test73",
                            Sex = 0
                        },
                        new
                        {
                            Id = 75,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 74.099999999999994,
                            IntV = 74,
                            Name = "Test74",
                            Sex = 0
                        },
                        new
                        {
                            Id = 76,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 75.099999999999994,
                            IntV = 75,
                            Name = "Test75",
                            Sex = 0
                        },
                        new
                        {
                            Id = 77,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 76.099999999999994,
                            IntV = 76,
                            Name = "Test76",
                            Sex = 0
                        },
                        new
                        {
                            Id = 78,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 77.099999999999994,
                            IntV = 77,
                            Name = "Test77",
                            Sex = 0
                        },
                        new
                        {
                            Id = 79,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 78.099999999999994,
                            IntV = 78,
                            Name = "Test78",
                            Sex = 0
                        },
                        new
                        {
                            Id = 80,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 79.099999999999994,
                            IntV = 79,
                            Name = "Test79",
                            Sex = 0
                        },
                        new
                        {
                            Id = 81,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 80.099999999999994,
                            IntV = 80,
                            Name = "Test80",
                            Sex = 0
                        },
                        new
                        {
                            Id = 82,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 81.099999999999994,
                            IntV = 81,
                            Name = "Test81",
                            Sex = 0
                        },
                        new
                        {
                            Id = 83,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 82.099999999999994,
                            IntV = 82,
                            Name = "Test82",
                            Sex = 0
                        },
                        new
                        {
                            Id = 84,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 83.099999999999994,
                            IntV = 83,
                            Name = "Test83",
                            Sex = 0
                        },
                        new
                        {
                            Id = 85,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 84.099999999999994,
                            IntV = 84,
                            Name = "Test84",
                            Sex = 0
                        },
                        new
                        {
                            Id = 86,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 85.099999999999994,
                            IntV = 85,
                            Name = "Test85",
                            Sex = 0
                        },
                        new
                        {
                            Id = 87,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 86.099999999999994,
                            IntV = 86,
                            Name = "Test86",
                            Sex = 0
                        },
                        new
                        {
                            Id = 88,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 87.099999999999994,
                            IntV = 87,
                            Name = "Test87",
                            Sex = 0
                        },
                        new
                        {
                            Id = 89,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 88.099999999999994,
                            IntV = 88,
                            Name = "Test88",
                            Sex = 0
                        },
                        new
                        {
                            Id = 90,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 89.099999999999994,
                            IntV = 89,
                            Name = "Test89",
                            Sex = 0
                        },
                        new
                        {
                            Id = 91,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 90.099999999999994,
                            IntV = 90,
                            Name = "Test90",
                            Sex = 0
                        },
                        new
                        {
                            Id = 92,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 91.099999999999994,
                            IntV = 91,
                            Name = "Test91",
                            Sex = 0
                        },
                        new
                        {
                            Id = 93,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 92.099999999999994,
                            IntV = 92,
                            Name = "Test92",
                            Sex = 0
                        },
                        new
                        {
                            Id = 94,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 93.099999999999994,
                            IntV = 93,
                            Name = "Test93",
                            Sex = 0
                        },
                        new
                        {
                            Id = 95,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 94.099999999999994,
                            IntV = 94,
                            Name = "Test94",
                            Sex = 0
                        },
                        new
                        {
                            Id = 96,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 95.099999999999994,
                            IntV = 95,
                            Name = "Test95",
                            Sex = 0
                        },
                        new
                        {
                            Id = 97,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 96.099999999999994,
                            IntV = 96,
                            Name = "Test96",
                            Sex = 0
                        },
                        new
                        {
                            Id = 98,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 97.099999999999994,
                            IntV = 97,
                            Name = "Test97",
                            Sex = 0
                        },
                        new
                        {
                            Id = 99,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 98.099999999999994,
                            IntV = 98,
                            Name = "Test98",
                            Sex = 0
                        },
                        new
                        {
                            Id = 100,
                            Created = new DateTimeOffset(new DateTime(2020, 3, 12, 12, 33, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 8, 0, 0, 0)),
                            DouV = 99.099999999999994,
                            IntV = 99,
                            Name = "Test99",
                            Sex = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
